server:
  port: 28085

nacosIp: 212.64.18.166

spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${nacosIp}:30000
        #注意:配置group的时候,必须配置一个namespace(这个值是从nacos控制台命名空间获取的ID值),这样才能设置权重和负载均衡
        namespace: rrrrrrrrr
        cluster-name: kkk
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          route-id-prefix: nacos-provider
      #          lower-case-service-id: true #是将请求路径上的服务名配置为小写
      routes: #数组都是-
        - id: myGatewayService1  #要求唯一值
          #uri可以直接写http://***地址转发的
          #此配置的值注册到Nacos中服务提供者的spring.application.name的值(最终要转发的服务地址) lb是指从nacos获取配置并遵循负载均衡(nacos内置  )
          uri: lb://nacos-provider
          #尤其要注意到路由匹配规则,详细参考https://www.jianshu.com/p/5e40bbc95eb9
          #访问http://localhost:28086/np/nacos-provider/nprovider/gateWayGetData 即可到对应的接口
          predicates:  #断言，返回布尔值 转发满足的条件
            - Path=/np/**
          filters:  #过滤器  在请求传递过程中做些手脚
            - StripPrefix=1 #在转发过程中去掉一层路径

logging:
  level:
    com.robben: trace



